version: "3.8"

services:
    pgdb:
        image: postgres:14.4
        container_name: pgdb
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data